# Generated by Django 6.0 on 2025-12-13 13:42

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(choices=[('B', 'B - Carro'), ('C', 'C - Caminhão'), ('D', 'D - Ônibus'), ('E', 'E - Carreta')], max_length=2, verbose_name='Categoria CNH')),
                ('cnh_numero', models.CharField(max_length=20, unique=True, verbose_name='Número da CNH')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_rota', 'Em Rota'), ('disponivel', 'Disponível')], default='disponivel', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(default=core.models.generate_codigo_rastreio, max_length=20, unique=True, verbose_name='Código de Rastreio')),
                ('endereco_origem', models.CharField(max_length=200, verbose_name='Endereço de Origem')),
                ('endereco_destino', models.CharField(max_length=200, verbose_name='Endereço de Destino')),
                ('cep_origem', models.CharField(default='00000-000', max_length=9, verbose_name='CEP Origem')),
                ('cep_destino', models.CharField(max_length=9, verbose_name='CEP Destino')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada'), ('remarcada', 'Remarcada')], default='pendente', max_length=20, verbose_name='Status')),
                ('capacidade_necessaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade Necessária (unidades)')),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Frete')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_entrega_prevista', models.DateField(verbose_name='Data de Entrega Prevista')),
                ('data_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega Real')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.cliente', verbose_name='Cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='core.motorista', verbose_name='Motorista Responsável')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='Status Novo')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.entrega', verbose_name='Entrega')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motorista', verbose_name='Motorista que Atualizou')),
            ],
            options={
                'verbose_name': 'Histórico de Entrega',
                'verbose_name_plural': 'Históricos de Entrega',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Rota')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_rota', models.DateField(verbose_name='Data da Rota')),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=20, verbose_name='Status')),
                ('capacidade_total_utilizada', models.IntegerField(default=0, verbose_name='Capacidade Total Utilizada')),
                ('km_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='KM Total Estimado')),
                ('km_total_real', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='KM Total Real')),
                ('tempo_estimado_minutos', models.IntegerField(default=0, verbose_name='Tempo Estimado (minutos)')),
                ('tempo_real_minutos', models.IntegerField(default=0, verbose_name='Tempo Real (minutos)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('entregas', models.ManyToManyField(blank=True, related_name='rotas_associadas', to='core.entrega', verbose_name='Entregas')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='core.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_rota', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_na_rota', to='core.rota', verbose_name='Rota'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('van', 'Van'), ('caminhao', 'Caminhão')], max_length=20, verbose_name='Tipo de Veículo')),
                ('capacidade_maxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade Máxima (unidades)')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('km_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quilometragem Atual')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Manutenção')], default='disponivel', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('motorista_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_associados', to='core.motorista', verbose_name='Motorista Atual')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='core.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['codigo_rastreio'], name='core_entreg_codigo__82652d_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['status'], name='core_entreg_status_990eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['data_entrega_prevista'], name='core_entreg_data_en_33a08f_idx'),
        ),
    ]
